import turtle
'''
Drawing a flower with turtle module
'''
def draw_flower():
	window = turtle.Screen()
	window.bgcolor("white")
	drawer = turtle.Turtle()
	drawer.shape("turtle")
	drawer.color("red")
	drawer.speed(5)
	drawer.fd(15)
	drawer.rt(90)
	drawer.fd(100)
	drawer.rt(90)
	drawer.fd(15)
	drawer.rt(90)
	drawer.fd(100)
	drawer.color("yellow")
	drawer.rt(90)
	drawer.fd(20)
	drawer.rt(90)
	drawer.fd(100)
	drawer.rt(90)
	drawer.fd(15)
	drawer.rt(90)
	drawer.fd(100)
	drawer.color("blue")
	drawer.rt(90)
	drawer.fd(20)
	drawer.rt(90)
	drawer.fd(100)
	drawer.rt(90)
	drawer.fd(15)
	drawer.rt(90)
	drawer.fd(100)
	drawer.lt(90)
	drawer.fd(10)
	drawer.color("green")
	drawer.rt(20)
	drawer.fd(80)
	drawer.rt(90)
	drawer.color("blue")
	drawer.fd(3)
	drawer.rt(92)
	drawer.fd(85)
	n = 0
	while n<13:
		drawer.color("blue")
		drawer.lt(83)
		drawer.fd(3)
		drawer.lt(90)
		drawer.fd(83)
		drawer.color("green")
		drawer.rt(93)
		drawer.fd(3)
		drawer.rt(90)
		drawer.fd(83)
		n+=1
	window.exitonclick()
draw_flower()